twitter-to-kafka-service:
  twitter-keywords:
    - java
    - microservices
    - nextjs
    - react
    - reactjs
    - typescript
    - golang
    - go
  mock-sleep-ms: 10000

retry-config:
  initialInterval: 1000
  maxInterval: 10000
  multiplier: 2
  maxAttempt: 3
  sleepTimeMs: 2000

kafka-config:
  bootstrap-server: localhost:19092, localhost:29092, localhost:39092
  schema-registry-url-key: schema.registry.url
  schema-registry-url: http://localhost:8081
  topic-name: twitter-topic
  topic-name-to-create:
    - twitter-topic
  number-of-partitions: 3
  replication-factor: 3