server:
  port: 8888
logging:
  level:
    root: info
    org.springframework.cloud.config: debug

spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: file://home/sagar/codingworks/javaspring/microservice-demo/config-server-repository
          clone-on-start: true
      fail-fast: true
