server:
  port: 8888
logging:
  level:
    root: info
    org.springframework.cloud.config: debug

spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sagarrajak/spring-config-microservice
#          uri: file://home/sagar/codingworks/javaspring/microservice-demo/config-server-repository
          clone-on-start: true
          password: ${GITHUB_TOKEN}
          username: something
      fail-fast: true