spring:
  application:
    name: config-client
  profiles:
    active: kafka_to_elastic
  config:
    import: "configserver:http://localhost:8888"


server:
  port: 8182

#logging:
#  level:
#    org.apache.http.wire: DEBUG
#    org.elasticsearch.client: DEBUG
#    org.apache.http: DEBUG
